### ISSUE TITLE
Flash and RAM usage computation

### ISSUE THREAD

**Issue by maxgerhardt** [sonydevworld/spresense-arduino-compatible#176]
https://github.com/sonydevworld/spresense-arduino-compatible/blob/1eba2ab7e8d79202ad02f4442a5a1f9161d93372/Arduino15/packages/SPRESENSE/hardware/spresense/1.0.0/platform.txt#L95-L96

How can these two be equal? Flash and RAM usage should be calculated from different ELF sections, no? 

This causes the Arduino IDE to always show Flash usage and RAM usage as the exact same number.

When I build the ELF file, I get the sections
```
.pio\build\spresense\firmware.elf  :

section             size        addr
.text             135804   218103808
.init_section          4   218239612
.ARM.exidx             8   218239616
.data               2244   218239624
.bss               11344   218242048
.comment             223           0
.ARM.attributes       50           0
.debug_abbrev      10853           0
.debug_info        60647           0
.debug_line        24462           0
.debug_aranges      1680           0
.debug_loc         25913           0
.debug_ranges       3536           0
.debug_str         13454           0
.debug_frame        5692           0
Total             295914
```

**Comment by SPRESENSE** [comment]
@maxgerhardt san,

Flash and RAM usage are used with different meanings from the original.
Please see the document for more details.
https://developer.sony.com/develop/spresense/docs/arduino_developer_guide_en.html#_memory_usage

In SPRESENSE, all the contents of Flash memory are loaded into SRAM and then executed on SRAM.
Programs often do not work because they cannot allocate memory dynamically from the heap area of the SRAM.
To prevent this problem, the remaining heap area is indicated by calculating the program size including bss.

Thanks.

**Comment by SPRESENSE** [comment]
As previously commented, this is a known constraint, not an issue.
Close #176.
